### ISSUE TITLE
URL changed 

### ISSUE THREAD

**Issue by RISHABHAGRAWALZRA** [gaurav1620/vaccine_notifier#2]
The URL used for fetching the Get vaccination sessions by the district for 7 days is now changed to "/v2/appointment/sessions/public/calendarByDistrict" means it also consist of the "public" keyword in this 

![image](https://user-images.githubusercontent.com/43982251/120216873-2c873800-c255-11eb-968d-37a6daedaff9.png)

**Comment by gaurav1620** [comment]
Hello,  
Thanks for pointing out the issue. It has been resolved in https://github.com/gaurav1620/vaccine_notifier/commit/df1860bc0b2c84e2f6cbb0587ed6a43d49a69c1b

**Comment by RISHABHAGRAWALZRA** [comment]
My pleasure : )
